services:
  db:
    image: mysql:8.0
    container_name: receipt-db
    restart: always
    environment:
      MYSQL_DATABASE: receipt_db
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d

  server:
    build: ./server
    container_name: receipt-server
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=receipt_db
    depends_on:
      - db

  client:
    build:
      context: ./client
      args:
        - NEXT_PUBLIC_API_URL=http://localhost:8080
    container_name: receipt-client
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080
      - ALLOWED_DEV_ORIGINS=192.168.50.18,localhost:3000
    depends_on:
      - server
