name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: 'read' # コードのチェックアウトに必要

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }} # サービスアカウントキーのJSONをSecretから読み込む

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker
        run: gcloud auth configure-docker ${{ secrets.GAR_DOMAIN }}-docker.pkg.dev

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.GAR_REPOSITORY }}:${{ github.sha }} -f server/Dockerfile server
          docker push ${{ secrets.GAR_REPOSITORY }}:${{ github.sha }}:latest
          echo "Image pushed: ${{ secrets.GAR_REPOSITORY }}:${{ github.sha }}"
